//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwââ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChiTietDH
    {
        [DisplayName("Mã đơn hàng")]
        public string MaDonHang { get; set; }
        [DisplayName("Mã chi tiết sản phẩm")]
        public string MaChiTietSP { get; set; }
        [DisplayName("Số lượng mua")]
        public Nullable<int> SoLuongMua { get; set; }
        [DisplayName("Đơn Giá Bán")]
        public Nullable<long> DonGiaBan { get; set; }
        [DisplayName("Chi tiết sản phẩm bán")]

        public virtual ChiTietSPBan ChiTietSPBan { get; set; }
        [DisplayName("Đơn hàng")]
        public virtual DonHang DonHang { get; set; }
        
    }
}
