//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwââ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
        [DisplayName("Mã sản phẩm")]
        public string MaSanPham { get; set; }
        [DisplayName("Tên sản phẩm")]
        [RegularExpression(@"^[\p{L}].*$", ErrorMessage = "Tên sản phẩm phải bắt đầu bằng một chữ cái.")]
        public string TenSanPham { get; set; }
        [DisplayName("Mã phân loại")]
        public string MaPhanLoai { get; set; }
        [DisplayName("Giá nhập")]
        public Nullable<long> GiaNhap { get; set; }
        [DisplayName("Đơn giá bán nhỏ nhất")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Please enter sa valid numeric value.")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Chỉ được nhập số.")]
        [DisplayName("Đơn giá bán lớn nhất")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        [DisplayName("Trạng thái")]
        public Nullable<bool> TrangThai { get; set; }
        [DisplayName("Mô tả ngắn")]
        [RegularExpression(@"^[\p{L}].*$", ErrorMessage = "Mô tả ngắn phải bắt đầu bằng một chữ cái.")]
        public string MoTaNgan { get; set; }
        [DisplayName("Ảnh đại diện")]
      /*  [RegularExpression(@"\.jpg$", ErrorMessage = "Please upload a valid JPG image.")]*/
        public string AnhDaiDien { get; set; }
        [DisplayName("Nổi bật")]
        public Nullable<bool> NoiBat { get; set; }

        [DisplayName("Mã phân loại phụ")]
        public string MaPhanLoaiPhu { get; set; }

        [DisplayName("Phân loại")]
        public virtual PhanLoai PhanLoai { get; set; }
        [DisplayName("Phân loại phụ")]
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DisplayName("Sản phẩm theo mẫu")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }



    }
}

